name: medpal
description: "MedPal+: Smart Medicine Reminder & Health Management App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Core Supabase package for database and auth
  supabase_flutter: ^2.12.0
  
  # Required for native Google Sign-In on Android/iOS
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Asset section for your Google logo and app images
  assets:
    - assets/images/